CREATE TABLE "jnHooperMenu_account" (
	"user_id" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_account_id" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "jnHooperMenu_account_provider_provider_account_id_pk" PRIMARY KEY("provider","provider_account_id")
);
--> statement-breakpoint
CREATE TABLE "jnHooperMenu_household" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"head_of_household_id" varchar NOT NULL,
	"default_menu_id" varchar
);
--> statement-breakpoint
CREATE TABLE "jnHooperMenu_item" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"last_selected" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"image_url" text NOT NULL,
	"link" text,
	"description" text,
	"is_visible" boolean DEFAULT true NOT NULL,
	"menu_id" varchar NOT NULL,
	"metadata" jsonb,
	"position" integer NOT NULL,
	CONSTRAINT "jnHooperMenu_item_menu_id_position_unique" UNIQUE("menu_id","position")
);
--> statement-breakpoint
CREATE TABLE "jnHooperMenu_menu" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"created_by" varchar(255),
	"last_updated_by" varchar(255),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	"household_id" varchar(255) NOT NULL,
	"is_private" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "jnHooperMenu_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "jnHooperMenu_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "jnHooperMenu_session" (
	"session_token" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "jnHooperMenu_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"email_verified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255),
	"default_household_id" varchar(255),
	"default_menu_id" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "jnHooperMenu_users_to_households" (
	"user_id" varchar(255) NOT NULL,
	"household_id" varchar(255) NOT NULL,
	CONSTRAINT "jnHooperMenu_users_to_households_user_id_household_id_pk" PRIMARY KEY("user_id","household_id")
);
--> statement-breakpoint
CREATE TABLE "jnHooperMenu_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "jnHooperMenu_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "jnHooperMenu_account" ADD CONSTRAINT "jnHooperMenu_account_user_id_jnHooperMenu_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."jnHooperMenu_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "jnHooperMenu_item" ADD CONSTRAINT "jnHooperMenu_item_created_by_jnHooperMenu_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."jnHooperMenu_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "jnHooperMenu_item" ADD CONSTRAINT "jnHooperMenu_item_updated_by_jnHooperMenu_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."jnHooperMenu_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "jnHooperMenu_menu" ADD CONSTRAINT "jnHooperMenu_menu_created_by_jnHooperMenu_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."jnHooperMenu_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "jnHooperMenu_menu" ADD CONSTRAINT "jnHooperMenu_menu_last_updated_by_jnHooperMenu_user_id_fk" FOREIGN KEY ("last_updated_by") REFERENCES "public"."jnHooperMenu_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "jnHooperMenu_menu" ADD CONSTRAINT "jnHooperMenu_menu_household_id_jnHooperMenu_household_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."jnHooperMenu_household"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "jnHooperMenu_post" ADD CONSTRAINT "jnHooperMenu_post_created_by_jnHooperMenu_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."jnHooperMenu_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "jnHooperMenu_session" ADD CONSTRAINT "jnHooperMenu_session_user_id_jnHooperMenu_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."jnHooperMenu_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "jnHooperMenu_users_to_households" ADD CONSTRAINT "jnHooperMenu_users_to_households_user_id_jnHooperMenu_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."jnHooperMenu_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "jnHooperMenu_users_to_households" ADD CONSTRAINT "jnHooperMenu_users_to_households_household_id_jnHooperMenu_household_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."jnHooperMenu_household"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "jnHooperMenu_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "jnHooperMenu_post" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "name_idx" ON "jnHooperMenu_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "jnHooperMenu_session" USING btree ("user_id");